name: lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.x
    - run: npm install
    - run: npm run lint:strict
